### ISSUE TITLE
Cubemap generator issue 

### ISSUE THREAD

**Issue by OBRISON** [ruarai/CompilePal#52] opened 2018-04-20 15:54 UTC
So I closed my game client.And compiled my map and I got this error:

Something broke:
System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at CompilePalX.Compilers.CubemapProcess.FetchHDRLevels()
   at CompilePalX.Compilers.CubemapProcess.Run(CompileContext context)

I can send full compile log if needed.

**Comment by TheSwitchGuy** [comment] 2018-04-21 18:39
I've had this before. Open up the game config json and check that all the paths to the compiling tools are right. Make sure it's right for vbspinfo and bsppack.

**Comment by CRO557** [comment] 2018-04-23 14:10
Everything is fine,I even deleted config and its still the same.

**Comment by maxdup** [comment] 2018-04-23 18:35
Okay let's troubleshoot this. If I'm understanding this error correctly, the file not being found in the error message is vbspinfo.exe. Can you check in your compilepal folder for GameConfiguration/gameConfigs.json. Open that file with notepad and you'll find a configuration for each game, you'll need to check for me the path for "VBSPInfo" on the relevant game. Check that the path is correct and make sure that vbspinfo.exe exists at that location (don't mind the double slashes, these count as one). I'm not sure what the problem is exactly but I'm betting it's going to be in there.

**Comment by maxdup** [comment] 2018-08-20 16:16
@Servius alright, so the issue seems to be that Garry's mod does not ship with vbspinfo.exe in its GarrysMod\bin folder. The cubemap generator relies on vbspinfo.exe to function properly. The short term fix for you might be to copy vbspinfo.exe from an other source game into your bin folder. But I'll be changing the cubemap generator so that it does not rely on vbspinfo.exe in the future.

**Comment by Exactol** [comment] 2023-01-28 19:46
This has been fixed in the latest prerelease

**Closed by Exactol** 2023-01-28 19:46 UTC
