### ISSUE TITLE
PACK screenoverlays (and sounds) triggered through commands

### ISSUE THREAD

**Issue by granis48** [ruarai/CompilePal#166] opened 2022-01-28 22:49 UTC
Many mappers use point_clientcommand to trigger screenoverlays or sounds (using the "r_screenoverlay x" or "play y" commands), I didn't try packing any sounds like this but the screenoverlay one right here didn't pack automatically so im assuming this isn't one of the checks for it. 

![image](https://user-images.githubusercontent.com/52294733/151632015-6c8c9262-de7d-4bc2-b7af-7fb7a06cf96c.png)

**Comment by Exactol** [comment] 2022-03-08 21:04
The play commands should be packed, let me know if that isn't working. I just pushed a fix for packing r_screenoverlay, you can download it here: https://github.com/ruarai/CompilePal/releases/tag/v027.17

**Comment by Exactol** [comment] 2023-01-28 20:01
Closing stale issues, please try the latest prerelease and if the issue is still happening feel free to reopen

**Closed by Exactol** 2023-01-28 20:01 UTC
Labels: enhancement
